@startuml
skinparam classAttributeIconSize 0

class Question {
    - id : int
    - question : string
}

class Reponse {
    - id : int
    - reponse : string
    - vraie : bool
}

class Categorie {
    - id : int
    - nom : string
}

Categorie"1..1"--"1..*"Question
Reponse"1..*"--"1..1"Question
@enduml